nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: ['Link']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin:
                - 'http://localhost:5173'
                - 'http://127.0.0.1:5173'
                - 'https://ai-cv-analyzer-6pwjplru7-ai-cv-matcher.vercel.app'
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            expose_headers: ['Link']
            max_age: 3600